# Collect data using FastF1
### by Benjamin PORTERIE

### This notebook has been created to show the process of catching, visualizing and predicting data from the api fastF1

## 1/ Requirements

In [1]:
import fastf1
from fastf1.livetiming.data import LiveTimingData
import pandas as pd
import numpy as np

You must create a cach directory to prevent downloading duplicates and to save some time.

In [2]:
fastf1.Cache.enable_cache(r'C:\Users\benja\OneDrive - De Vinci\S7_ESILV\cach_directory')

 #### Inputs of the selected Grand Prix and session

In [3]:
year = 2021
raceNumber = 10
session_letter = 'R'
driver = 'HAM'

## 2/ Load Data

### 1/ Session data

In [38]:
session = fastf1.get_session(year, raceNumber, session_letter)
session

### 2/ Laps data

#### with telemetry

In [5]:
laps = session.load_laps(with_telemetry=True)

core           INFO 	Loading laps for Russian Grand Prix - Race [v2.1.11]
api            INFO 	No cached data found for timing_data. Loading data...
api            INFO 	Fetching timing data...
api            INFO 	Parsing timing data...
api            INFO 	Data has been written to cache!
api            INFO 	No cached data found for timing_app_data. Loading data...
api            INFO 	Fetching timing app data...
api            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
api            INFO 	No cached data found for driver_info. Loading data...
api            INFO 	Fetching driver list...
api            INFO 	Data has been written to cache!
api            INFO 	No cached data found for session_status_data. Loading data...
api            INFO 	Fetching session status data...
api            INFO 	Data has been written to cache!
utils          INFO 	NumExpr defaulting to 8 threads.
api            INFO 	No cached data found for track_status_data. Loading data...
api            INFO 	Fetching track status data...
api            INFO 	Data has been written to cache!
api            INFO 	No cached data found for car_data. Loading data...
api            INFO 	Fetching car data...
api            INFO 	Parsing car data...
api            INFO 	Data has been written to cache!
api            INFO 	No cached data found for position_data. Loading data...
api            INFO 	Fetching position data...
api            INFO 	Parsing position data...
api         WARNING 	Driver 241: Position data is incomplete!
api         WARNING 	Driver 242: Position data is incomplete!
api         WARNING 	Driver 243: Position data is incomplete!
api            INFO 	Data has been written to cache!
api            INFO 	No cached data found for weather_data. Loading data...
api            INFO 	Fetching weather data...
api            INFO 	Data has been written to cache!
core           INFO 	Loaded data for 20 drivers: ['33', '5', '31', '6', '3', '77', '44', '4', '7', '20', '63', '16', '99', '55', '8', '23', '11', '26', '18', '10']

In [6]:
laps.head()

,Time,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,...,SpeedST,Compound,TyreLife,FreshTyre,LapStartTime,Team,Driver,TrackStatus,IsAccurate,LapStartDate
0,0 days 00:35:40.827000,44,NaT,1.0,1.0,0 days 00:00:06.080000,NaT,NaT,0 days 00:00:49.188000,0 days 00:00:40.752000,...,300.0,SOFT,4.0,False,0 days 00:33:33.451000,Mercedes,HAM,24,False,2020-09-27 11:13:33.505
1,0 days 00:38:46.991000,44,NaT,2.0,1.0,NaT,NaT,0 days 00:01:28.085000,0 days 00:00:52.126000,0 days 00:00:45.964000,...,117.0,SOFT,5.0,False,0 days 00:35:40.827000,Mercedes,HAM,4,False,2020-09-27 11:15:40.881
2,0 days 00:41:39.305000,44,NaT,3.0,1.0,NaT,NaT,0 days 00:01:11.631000,0 days 00:00:57.383000,0 days 00:00:43.313000,...,109.0,SOFT,6.0,False,0 days 00:38:46.991000,Mercedes,HAM,4,False,2020-09-27 11:18:47.045
3,0 days 00:44:31.951000,44,NaT,4.0,1.0,NaT,NaT,0 days 00:01:09.954000,0 days 00:00:57.322000,0 days 00:00:45.364000,...,186.0,SOFT,7.0,False,0 days 00:41:39.305000,Mercedes,HAM,4,False,2020-09-27 11:21:39.359
4,0 days 00:47:25.709000,44,NaT,5.0,1.0,NaT,NaT,0 days 00:01:03.969000,0 days 00:00:58.181000,0 days 00:00:51.619000,...,152.0,SOFT,8.0,False,0 days 00:44:31.951000,Mercedes,HAM,4,False,2020-09-27 11:24:32.005

In [7]:
laps.columns

Index(['Time', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint', 'PitOutTime',
       'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time',
       'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime',
       'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'Compound', 'TyreLife',
       'FreshTyre', 'LapStartTime', 'Team', 'Driver', 'TrackStatus',
       'IsAccurate', 'LapStartDate'],
      dtype='object')

In [8]:
laps.describe()

,Time,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,TyreLife,LapStartTime
count,948,856,948.000000,948.000000,42,24,926,946,946,926,946,946,840.000000,946.000000,922.000000,870.00000,676.000000,948
mean,0 days 01:24:20.137561181,0 days 00:01:41.889068925,26.723629,1.743671,0 days 00:44:47.592857142,0 days 01:17:47.979000,0 days 00:00:39.452711663,0 days 00:00:37.128562367,0 days 00:00:31.520883720,0 days 01:24:14.024911447,0 days 01:23:54.791070824,0 days 01:24:26.321563424,240.870238,285.415433,155.721258,284.58046,15.211538,0 days 01:22:31.965731012
std,0 days 00:26:13.835884620,0 days 00:00:04.033059054,15.214537,0.623977,0 days 00:43:07.036476977,0 days 00:24:03.779697232,0 days 00:00:10.496959368,0 days 00:00:06.585573243,0 days 00:00:04.443527176,0 days 00:25:36.923731661,0 days 00:26:12.133524887,0 days 00:26:09.734951896,34.082157,46.608214,16.322395,48.81915,9.355113,0 days 00:26:24.668116371
min,0 days 00:35:40.827000,0 days 00:01:37.030000,0.000000,1.000000,0 days 00:00:06.080000,0 days 00:35:57.073000,0 days 00:00:34.631000,0 days 00:00:33.500000,0 days 00:00:28.505000,0 days 00:37:08.914000,0 days 00:35:00.075000,0 days 00:35:40.912000,80.000000,83.000000,47.000000,73.00000,1.000000,0 days 00:33:33.451000
25%,0 days 01:02:35.892750,0 days 00:01:39.841750,14.000000,1.000000,0 days 00:00:06.080000,0 days 01:06:15.561250,0 days 00:00:35.745000,0 days 00:00:34.544750,0 days 00:00:29.588750,0 days 01:02:07.345500,0 days 01:02:09.336750,0 days 01:02:39.197500,244.000000,293.000000,157.000000,292.00000,8.000000,0 days 01:00:55.719250
50%,0 days 01:24:49.757000,0 days 00:01:41.240000,27.000000,2.000000,0 days 00:50:13.002500,0 days 01:12:05.486500,0 days 00:00:36.098000,0 days 00:00:35.024000,0 days 00:00:30.104500,0 days 01:24:17.842500,0 days 01:24:23.619500,0 days 01:24:53.225000,252.000000,298.000000,160.000000,299.00000,14.000000,0 days 01:23:08.628500
75%,0 days 01:46:54.533750,0 days 00:01:42.142000,40.000000,2.000000,0 days 01:19:24.140750,0 days 01:29:53.933500,0 days 00:00:36.465500,0 days 00:00:35.498250,0 days 00:00:30.584750,0 days 01:46:13.744500,0 days 01:46:25.111250,0 days 01:46:54.931250,257.000000,302.000000,162.000000,304.00000,22.000000,0 days 01:45:14.762000
max,0 days 02:09:06.812000,0 days 00:02:12.717000,53.000000,4.000000,0 days 02:05:39.752000,0 days 02:05:10.094000,0 days 00:01:28.289000,0 days 00:01:11.370000,0 days 00:00:51.619000,0 days 02:08:03.733000,0 days 02:08:37.582000,0 days 02:09:06.812000,271.000000,332.000000,172.000000,332.00000,46.000000,0 days 02:07:28.383000

In [9]:
laps.shape

(948, 26)

#### Without telemetry

In [10]:
session_notel = fastf1.get_session(2019, 8, 'R')
laps_notel = session_notel.load_laps(with_telemetry=False)

core           INFO 	Loading laps for French Grand Prix - Race [v2.1.11]
api            INFO 	Using cached data for timing_data
api            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
api            INFO 	Using cached data for driver_info
api            INFO 	Using cached data for session_status_data
api            INFO 	Using cached data for track_status_data
api            INFO 	Using cached data for weather_data
core           INFO 	Loaded data for 20 drivers: ['44', '77', '16', '33', '4', '55', '5', '3', '10', '99', '23', '7', '27', '11', '20', '8', '18', '88', '26', '63']

In [11]:
laps_notel

,Time,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,...,SpeedFL,SpeedST,Compound,TyreLife,FreshTyre,LapStartTime,Team,Driver,TrackStatus,IsAccurate
0,0 days 00:35:07.239000,44,NaT,1,1,0 days 00:00:07.397000,NaT,NaT,0 days 00:00:29.624000,0 days 00:00:42.478000,...,284.0,307.0,MEDIUM,5.0,False,0 days 00:33:25.039000,Mercedes,HAM,1,False
1,0 days 00:36:44.671000,44,0 days 00:01:37.432000,2,1,NaT,NaT,0 days 00:00:24.852000,0 days 00:00:30.172000,0 days 00:00:42.408000,...,285.0,299.0,MEDIUM,6.0,False,0 days 00:35:07.239000,Mercedes,HAM,1,True
2,0 days 00:38:21.422000,44,0 days 00:01:36.751000,3,1,NaT,NaT,0 days 00:00:24.570000,0 days 00:00:29.666000,0 days 00:00:42.515000,...,285.0,299.0,MEDIUM,7.0,False,0 days 00:36:44.671000,Mercedes,HAM,1,True
3,0 days 00:39:57.712000,44,0 days 00:01:36.290000,4,1,NaT,NaT,0 days 00:00:24.255000,0 days 00:00:29.640000,0 days 00:00:42.395000,...,284.0,302.0,MEDIUM,8.0,False,0 days 00:38:21.422000,Mercedes,HAM,1,True
4,0 days 00:41:33.691000,44,0 days 00:01:35.979000,5,1,NaT,NaT,0 days 00:00:24.282000,0 days 00:00:29.660000,0 days 00:00:42.037000,...,285.0,302.0,MEDIUM,9.0,False,0 days 00:39:57.712000,Mercedes,HAM,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1032,0 days 01:52:03.743000,63,0 days 00:01:37.962000,47,3,NaT,NaT,0 days 00:00:24.320000,0 days 00:00:29.854000,0 days 00:00:43.788000,...,290.0,302.0,MEDIUM,14.0,True,0 days 01:50:25.781000,Williams,RUS,2,True
1033,0 days 01:53:50.941000,63,0 days 00:01:47.198000,48,3,NaT,NaT,0 days 00:00:24.859000,0 days 00:00:33.873000,0 days 00:00:48.466000,...,290.0,298.0,MEDIUM,15.0,True,0 days 01:52:03.743000,Williams,RUS,267,False
1034,0 days 01:55:27.190000,63,0 days 00:01:36.249000,49,3,NaT,NaT,0 days 00:00:24.327000,0 days 00:00:29.585000,0 days 00:00:42.337000,...,289.0,298.0,MEDIUM,16.0,True,0 days 01:53:50.941000,Williams,RUS,1,True
1035,0 days 01:57:03.026000,63,0 days 00:01:35.836000,50,3,NaT,NaT,0 days 00:00:24.266000,0 days 00:00:29.582000,0 days 00:00:41.988000,...,290.0,305.0,MEDIUM,17.0,True,0 days 01:55:27.190000,Williams,RUS,1,True
1036,0 days 01:58:38.856000,63,0 days 00:01:35.830000,51,3,NaT,NaT,0 days 00:00:24.332000,0 days 00:00:29.517000,0 days 00:00:41.981000,...,289.0,298.0,MEDIUM,18.0,True,0 days 01:57:03.026000,Williams,RUS,1,True

#### a) Data from a specific driver

In [12]:
drivers = pd.unique(laps['Driver'])
drivers

array(['HAM', 'VER', 'BOT', 'PER', 'RIC', 'SAI', 'OCO', 'NOR', 'GAS',
       'LEC', 'KVY', 'STR', 'RUS', 'VET', 'ALB', 'GRO', 'GIO', 'MAG',
       'RAI', 'LAT'], dtype=object)

In [13]:
laps_driver = laps.pick_driver(driver)
laps_driver

,Time,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,...,SpeedST,Compound,TyreLife,FreshTyre,LapStartTime,Team,Driver,TrackStatus,IsAccurate,LapStartDate
0,0 days 00:35:40.827000,44,NaT,1.0,1.0,0 days 00:00:06.080000,NaT,NaT,0 days 00:00:49.188000,0 days 00:00:40.752000,...,300.0,SOFT,4.0,False,0 days 00:33:33.451000,Mercedes,HAM,24,False,2020-09-27 11:13:33.505
1,0 days 00:38:46.991000,44,NaT,2.0,1.0,NaT,NaT,0 days 00:01:28.085000,0 days 00:00:52.126000,0 days 00:00:45.964000,...,117.0,SOFT,5.0,False,0 days 00:35:40.827000,Mercedes,HAM,4,False,2020-09-27 11:15:40.881
2,0 days 00:41:39.305000,44,NaT,3.0,1.0,NaT,NaT,0 days 00:01:11.631000,0 days 00:00:57.383000,0 days 00:00:43.313000,...,109.0,SOFT,6.0,False,0 days 00:38:46.991000,Mercedes,HAM,4,False,2020-09-27 11:18:47.045
3,0 days 00:44:31.951000,44,NaT,4.0,1.0,NaT,NaT,0 days 00:01:09.954000,0 days 00:00:57.322000,0 days 00:00:45.364000,...,186.0,SOFT,7.0,False,0 days 00:41:39.305000,Mercedes,HAM,4,False,2020-09-27 11:21:39.359
4,0 days 00:47:25.709000,44,NaT,5.0,1.0,NaT,NaT,0 days 00:01:03.969000,0 days 00:00:58.181000,0 days 00:00:51.619000,...,152.0,SOFT,8.0,False,0 days 00:44:31.951000,Mercedes,HAM,4,False,2020-09-27 11:24:32.005
5,0 days 00:49:05.765000,44,0 days 00:01:40.056000,6.0,1.0,NaT,NaT,0 days 00:00:35.936000,0 days 00:00:34.721000,0 days 00:00:29.399000,...,299.0,SOFT,9.0,False,0 days 00:47:25.709000,Mercedes,HAM,1,False,2020-09-27 11:27:25.763
6,0 days 00:50:47.106000,44,0 days 00:01:41.341000,7.0,1.0,NaT,NaT,0 days 00:00:36.469000,0 days 00:00:35.131000,0 days 00:00:29.741000,...,292.0,SOFT,10.0,False,0 days 00:49:05.765000,Mercedes,HAM,1,True,2020-09-27 11:29:05.819
7,0 days 00:52:27.985000,44,0 days 00:01:40.879000,8.0,1.0,NaT,NaT,0 days 00:00:36.361000,0 days 00:00:34.969000,0 days 00:00:29.549000,...,288.0,SOFT,11.0,False,0 days 00:50:47.106000,Mercedes,HAM,1,True,2020-09-27 11:30:47.160
8,0 days 00:54:09.710000,44,0 days 00:01:41.725000,9.0,1.0,NaT,NaT,0 days 00:00:36.278000,0 days 00:00:35.244000,0 days 00:00:30.203000,...,291.0,SOFT,12.0,False,0 days 00:52:27.985000,Mercedes,HAM,1,True,2020-09-27 11:32:28.039
9,0 days 00:55:50.772000,44,0 days 00:01:41.062000,10.0,1.0,NaT,NaT,0 days 00:00:36.137000,0 days 00:00:35.129000,0 days 00:00:29.796000,...,300.0,SOFT,13.0,False,0 days 00:54:09.710000,Mercedes,HAM,1,True,2020-09-27 11:34:09.764
10,0 days 00:57:32.293000,44,0 days 00:01:41.521000,11.0,1.0,NaT,NaT,0 days 00:00:36.322000,0 days 00:00:35.366000,0 days 00:00:29.833000,...,297.0,SOFT,14.0,False,0 days 00:55:50.772000,Mercedes,HAM,1,True,2020-09-27 11:35:50.826
11,0 days 00:59:13.562000,44,0 days 00:01:41.269000,12.0,1.0,NaT,NaT,0 days 00:00:36.346000,0 days 00:00:35.147000,0 days 00:00:29.776000,...,298.0,SOFT,15.0,False,0 days 00:57:32.293000,Mercedes,HAM,1,True,2020-09-27 11:37:32.347
12,0 days 01:00:54.322000,44,0 days 00:01:40.760000,13.0,1.0,NaT,NaT,0 days 00:00:36.235000,0 days 00:00:35.004000,0 days 00:00:29.521000,...,295.0,SOFT,16.0,False,0 days 00:59:13.562000,Mercedes,HAM,1,True,2020-09-27 11:39:13.616
13,0 days 01:02:34.095000,44,0 days 00:01:39.773000,14.0,1.0,NaT,NaT,0 days 00:00:35.883000,0 days 00:00:34.541000,0 days 00:00:29.349000,...,300.0,SOFT,17.0,False,0 days 01:00:54.322000,Mercedes,HAM,1,True,2020-09-27 11:40:54.376
14,0 days 01:04:13.788000,44,0 days 00:01:39.693000,15.0,1.0,NaT,NaT,0 days 00:00:35.641000,0 days 00:00:34.587000,0 days 00:00:29.465000,...,299.0,SOFT,18.0,False,0 days 01:02:34.095000,Mercedes,HAM,1,True,2020-09-27 11:42:34.149
15,0 days 01:05:58.723000,44,0 days 00:01:44.935000,16.0,1.0,NaT,0 days 01:05:50.572000,0 days 00:00:35.843000,0 days 00:00:34.586000,0 days 00:00:34.506000,...,NaN,SOFT,19.0,False,0 days 01:04:13.788000,Mercedes,HAM,1,False,2020-09-27 11:44:13.842
16,0 days 01:08:11.440000,44,0 days 00:02:12.717000,17.0,2.0,0 days 01:06:31.896000,NaT,0 days 00:01:08.399000,0 days 00:00:34.460000,0 days 00:00:29.858000,...,276.0,HARD,NaN,True,0 days 01:05:58.723000,Mercedes,HAM,1,False,2020-09-27 11:45:58.777
17,0 days 01:09:51.892000,44,0 days 00:01:40.452000,18.0,2.0,NaT,NaT,0 days 00:00:35.696000,0 days 00:00:34.219000,0 days 00:00:30.537000,...,306.0,HARD,NaN,True,0 days 01:08:11.440000,Mercedes,HAM,1,True,2020-09-27 11:48:11.494
18,0 days 01:11:31.727000,44,0 days 00:01:39.835000,19.0,2.0,NaT,NaT,0 days 00:00:35.525000,0 days 00:00:34.680000,0 days 00:00:29.630000,...,320.0,HARD,NaN,True,0 days 01:09:51.892000,Mercedes,HAM,1,True,2020-09-27 11:49:51.946
19,0 days 01:13:11.857000,44,0 days 00:01:40.130000,20.0,2.0,NaT,NaT,0 days 00:00:35.791000,0 days 00:00:34.562000,0 days 00:00:29.777000,...,298.0,HARD,NaN,True,0 days 01:11:31.727000,Mercedes,HAM,1,True,2020-09-27 11:51:31.781
20,0 days 01:14:52.005000,44,0 days 00:01:40.148000,21.0,2.0,NaT,NaT,0 days 00:00:35.784000,0 days 00:00:34.539000,0 days 00:00:29.825000,...,305.0,HARD,NaN,True,0 days 01:13:11.857000,Mercedes,HAM,1,True,2020-09-27 11:53:11.911
21,0 days 01:16:32.049000,44,0 days 00:01:40.044000,22.0,2.0,NaT,NaT,0 days 00:00:35.928000,0 days 00:00:34.406000,0 days 00:00:29.710000,...,303.0,HARD,NaN,True,0 days 01:14:52.005000,Mercedes,HAM,1,True,2020-09-27 11:54:52.059
22,0 days 01:18:11.879000,44,0 days 00:01:39.830000,23.0,2.0,NaT,NaT,0 days 00:00:35.795000,0 days 00:00:34.431000,0 days 00:00:29.604000,...,NaN,HARD,NaN,True,0 days 01:16:32.049000,Mercedes,HAM,1,True,2020-09-27 11:56:32.103
23,0 days 01:19:51.727000,44,0 days 00:01:39.848000,24.0,2.0,NaT,NaT,0 days 00:00:35.520000,0 days 00:00:34.540000,0 days 00:00:29.788000,...,306.0,HARD,NaN,True,0 days 01:18:11.879000,Mercedes,HAM,1,True,2020-09-27 11:58:11.933
24,0 days 01:21:31.444000,44,0 days 00:01:39.717000,25.0,2.0,NaT,NaT,0 days 00:00:35.727000,0 days 00:00:34.360000,0 days 00:00:29.630000,...,304.0,HARD,NaN,True,0 days 01:19:51.727000,Mercedes,HAM,1,True,2020-09-27 11:59:51.781
25,0 days 01:23:11.229000,44,0 days 00:01:39.785000,26.0,2.0,NaT,NaT,0 days 00:00:35.731000,0 days 00:00:34.522000,0 days 00:00:29.532000,...,305.0,HARD,NaN,True,0 days 01:21:31.444000,Mercedes,HAM,1,True,2020-09-27 12:01:31.498
26,0 days 01:24:51.027000,44,0 days 00:01:39.798000,27.0,2.0,NaT,NaT,0 days 00:00:35.664000,0 days 00:00:34.467000,0 days 00:00:29.667000,...,307.0,HARD,NaN,True,0 days 01:23:11.229000,Mercedes,HAM,1,True,2020-09-27 12:03:11.283
27,0 days 01:26:31.075000,44,0 days 00:01:40.048000,28.0,2.0,NaT,NaT,0 days 00:00:35.628000,0 days 00:00:34.540000,0 days 00:00:29.880000,...,NaN,HARD,NaN,True,0 days 01:24:51.027000,Mercedes,HAM,1,True,2020-09-27 12:04:51.081
28,0 days 01:28:11.094000,44,0 days 00:01:40.019000,29.0,2.0,NaT,NaT,0 days 00:00:35.631000,0 days 00:00:34.441000,0 days 00:00:29.947000,...,306.0,HARD,NaN,True,0 days 01:26:31.075000,Mercedes,HAM,1,True,2020-09-27 12:06:31.129
29,0 days 01:29:51.238000,44,0 days 00:01:40.144000,30.0,2.0,NaT,NaT,0 days 00:00:35.656000,0 days 00:00:34.723000,0 days 00:00:29.765000,...,314.0,HARD,NaN,True,0 days 01:28:11.094000,Mercedes,HAM,1,True,2020-09-27 12:08:11.148
30,0 days 01:31:30.586000,44,0 days 00:01:39.348000,31.0,2.0,NaT,NaT,0 days 00:00:35.537000,0 days 00:00:34.327000,0 days 00:00:29.484000,...,304.0,HARD,NaN,True,0 days 01:29:51.238000,Mercedes,HAM,1,True,2020-09-27 12:09:51.292
31,0 days 01:33:09.891000,44,0 days 00:01:39.305000,32.0,2.0,NaT,NaT,0 days 00:00:35.640000,0 days 00:00:34.192000,0 days 00:00:29.473000,...,302.0,HARD,NaN,True,0 days 01:31:30.586000,Mercedes,HAM,1,True,2020-09-27 12:11:30.640
32,0 days 01:34:48.986000,44,0 days 00:01:39.095000,33.0,2.0,NaT,NaT,0 days 00:00:35.452000,0 days 00:00:34.213000,0 days 00:00:29.430000,...,304.0,HARD,NaN,True,0 days 01:33:09.891000,Mercedes,HAM,1,True,2020-09-27 12:13:09.945
33,0 days 01:36:27.800000,44,0 days 00:01:38.814000,34.0,2.0,NaT,NaT,0 days 00:00:35.421000,0 days 00:00:34.151000,0 days 00:00:29.242000,...,305.0,HARD,NaN,True,0 days 01:34:48.986000,Mercedes,HAM,1,True,2020-09-27 12:14:49.040
34,0 days 01:38:06.498000,44,0 days 00:01:38.698000,35.0,2.0,NaT,NaT,0 days 00:00:35.374000,0 days 00:00:34.050000,0 days 00:00:29.274000,...,306.0,HARD,NaN,True,0 days 01:36:27.800000,Mercedes,HAM,1,True,2020-09-27 12:16:27.854
35,0 days 01:39:45.378000,44,0 days 00:01:38.880000,36.0,2.0,NaT,NaT,0 days 00:00:35.380000,0 days 00:00:34.260000,0 days 00:00:29.240000,...,303.0,HARD,NaN,True,0 days 01:38:06.498000,Mercedes,HAM,1,True,2020-09-27 12:18:06.552
36,0 days 01:41:24.187000,44,0 days 00:01:38.809000,37.0,2.0,NaT,NaT,0 days 00:00:35.395000,0 days 00:00:34.131000,0 days 00:00:29.283000,...,305.0,HARD,NaN,True,0 days 01:39:45.378000,Mercedes,HAM,1,True,2020-09-27 12:19:45.432
37,0 days 01:43:02.416000,44,0 days 00:01:38.229000,38.0,2.0,NaT,NaT,0 days 00:00:35.196000,0 days 00:00:33.924000,0 days 00:00:29.109000,...,NaN,HARD,NaN,True,0 days 01:41:24.187000,Mercedes,HAM,1,True,2020-09-27 12:21:24.241
38,0 days 01:44:40.727000,44,0 days 00:01:38.311000,39.0,2.0,NaT,NaT,0 days 00:00:35.103000,0 days 00:00:33.932000,0 days 00:00:29.276000,...,301.0,HARD,NaN,True,0 days 01:43:02.416000,Mercedes,HAM,1,True,2020-09-27 12:23:02.470
39,0 days 01:46:19.067000,44,0 days 00:01:38.340000,40.0,2.0,NaT,NaT,0 days 00:00:35.245000,0 days 00:00:33.885000,0 days 00:00:29.210000,...,303.0,HARD,NaN,True,0 days 01:44:40.727000,Mercedes,HAM,1,True,2020-09-27 12:24:40.781
40,0 days 01:47:57.551000,44,0 days 00:01:38.484000,41.0,2.0,NaT,NaT,0 days 00:00:35.029000,0 days 00:00:34.265000,0 days 00:00:29.190000,...,305.0,HARD,NaN,True,0 days 01:46:19.067000,Mercedes,HAM,1,True,2020-09-27 12:26:19.121
41,0 days 01:49:36.208000,44,0 days 00:01:38.657000,42.0,2.0,NaT,NaT,0 days 00:00:35.193000,0 days 00:00:34.006000,0 days 00:00:29.458000,...,302.0,HARD,NaN,True,0 days 01:47:57.551000,Mercedes,HAM,1,True,2020-09-27 12:27:57.605
42,0 days 01:51:27.870000,44,0 days 00:01:51.662000,43.0,2.0,NaT,NaT,0 days 00:00:43.886000,0 days 00:00:38.150000,0 days 00:00:29.626000,...,309.0,HARD,NaN,True,0 days 01:49:36.208000,Mercedes,HAM,67,False,2020-09-27 12:29:36.262
43,0 days 01:53:07.870000,44,0 days 00:01:40,44.0,2.0,NaT,NaT,0 days 00:00:36.060000,0 days 00:00:34.648000,0 days 00:00:29.292000,...,284.0,HARD,NaN,True,0 days 01:51:27.870000,Mercedes,HAM,1,True,2020-09-27 12:31:27.924
44,0 days 01:54:46.061000,44,0 days 00:01:38.191000,45.0,2.0,NaT,NaT,0 days 00:00:35.254000,0 days 00:00:33.827000,0 days 00:00:29.110000,...,312.0,HARD,NaN,True,0 days 01:53:07.870000,Mercedes,HAM,1,True,2020-09-27 12:33:07.924
45,0 days 01:56:24.491000,44,0 days 00:01:38.430000,46.0,2.0,NaT,NaT,0 days 00:00:35.304000,0 days 00:00:34.042000,0 days 00:00:29.084000,...,303.0,HARD,NaN,True,0 days 01:54:46.061000,Mercedes,HAM,1,True,2020-09-27 12:34:46.115
46,0 days 01:58:02.692000,44,0 days 00:01:38.201000,47.0,2.0,NaT,NaT,0 days 00:00:35.168000,0 days 00:00:33.937000,0 days 00:00:29.096000,...,304.0,HARD,NaN,True,0 days 01:56:24.491000,Mercedes,HAM,1,True,2020-09-27 12:36:24.545
47,0 days 01:59:40.767000,44,0 days 00:01:38.075000,48.0,2.0,NaT,NaT,0 days 00:00:35.159000,0 days 00:00:33.821000,0 days 00:00:29.095000,...,305.0,HARD,NaN,True,0 days 01:58:02.692000,Mercedes,HAM,1,True,2020-09-27 12:38:02.746
48,0 days 02:01:19.531000,44,0 days 00:01:38.764000,49.0,2.0,NaT,NaT,0 days 00:00:35.390000,0 days 00:00:34.219000,0 days 00:00:29.155000,...,304.0,HARD,NaN,True,0 days 01:59:40.767000,Mercedes,HAM,1,True,2020-09-27 12:39:40.821
49,0 days 02:02:58.069000,44,0 days 00:01:38.538000,50.0,2.0,NaT,NaT,0 days 00:00:35.425000,0 days 00:00:34.035000,0 days 00:00:29.078000,...,308.0,HARD,NaN,True,0 days 02:01:19.531000,Mercedes,HAM,1,True,2020-09-27 12:41:19.585
50,0 days 02:04:37.749000,44,0 days 00:01:39.680000,51.0,2.0,NaT,NaT,0 days 00:00:35.293000,0 days 00:00:33.932000,0 days 00:00:30.455000,...,299.0,HARD,NaN,True,0 days 02:02:58.069000,Mercedes,HAM,1,True,2020-09-27 12:42:58.123
51,0 days 02:06:16.389000,44,0 days 00:01:38.640000,52.0,2.0,NaT,NaT,0 days 00:00:34.979000,0 days 00:00:34.099000,0 days 00:00:29.562000,...,314.0,HARD,NaN,True,0 days 02:04:37.749000,Mercedes,HAM,1,True,2020-09-27 12:44:37.803
52,0 days 02:07:56.725000,44,0 days 00:01:40.336000,53.0,2.0,NaT,NaT,0 days 00:00:34.631000,0 days 00:00:35.122000,0 days 00:00:30.583000,...,NaN,HARD,NaN,True,0 days 02:06:16.389000,Mercedes,HAM,1,True,2020-09-27 12:46:16.443

#### b) Driver's Telemetries, full session

In [14]:
tele_driver = laps_driver.get_telemetry()

In [15]:
tele_driver

,Date,SessionTime,DriverAhead,DistanceToDriverAhead,Time,RPM,Speed,nGear,Throttle,Brake,DRS,Source,Distance,RelativeDistance,Status,X,Y,Z
1,2020-09-27 11:13:33.505,0 days 00:33:33.451000,,0.000000,0 days 00:00:00,9121,0,1,21,0,1,interpolation,0.015545,5.051651e-08,OnTrack,256,-2015,227
2,2020-09-27 11:13:33.573,0 days 00:33:33.519000,,0.000000,0 days 00:00:00.068000,9121,0,1,21,0,1,pos,0.005167,1.679082e-08,OnTrack,256,-2013,227
3,2020-09-27 11:13:33.593,0 days 00:33:33.539000,,0.000000,0 days 00:00:00.088000,9121,0,1,21,0,1,car,0.000000,0.000000e+00,OnTrack,256,-2012,227
4,2020-09-27 11:13:33.793,0 days 00:33:33.739000,,0.000000,0 days 00:00:00.288000,9121,0,1,21,0,1,pos,-0.043213,-1.404323e-07,OnTrack,256,-2013,227
5,2020-09-27 11:13:33.833,0 days 00:33:33.779000,,0.000000,0 days 00:00:00.328000,9121,0,1,21,0,1,car,0.000000,0.000000e+00,OnTrack,255,-2013,226
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49038,2020-09-27 12:47:56.486,0 days 02:07:56.432000,,692.313889,0 days 01:34:22.981000,9795,156,4,71,0,0,car,307695.755833,9.999298e-01,OnTrack,1307,-380,228
49039,2020-09-27 12:47:56.543,0 days 02:07:56.489000,,692.313889,0 days 01:34:23.038000,9332,158,4,69,0,0,pos,307698.283072,9.999380e-01,OnTrack,1293,-401,228
49040,2020-09-27 12:47:56.726,0 days 02:07:56.672000,,692.313889,0 days 01:34:23.221000,8870,161,4,67,0,0,car,307706.489167,9.999647e-01,OnTrack,1245,-467,227
49041,2020-09-27 12:47:56.763,0 days 02:07:56.709000,,692.313889,0 days 01:34:23.258000,9041,162,4,66,0,0,pos,307708.157369,9.999701e-01,OnTrack,1236,-481,228
49042,2020-09-27 12:47:56.779,0 days 02:07:56.725000,,692.313889,0 days 01:34:23.274000,9126,162,4,65,0,0,interpolation,307708.879533,9.999725e-01,OnTrack,1232,-487,228

In [16]:
tele_driver.shape

(49042, 18)

In [17]:
tele_driver.describe()

,SessionTime,DistanceToDriverAhead,Time,RPM,Speed,nGear,Throttle,Brake,DRS,Distance,RelativeDistance,X,Y,Z
count,49042,49042.000000,49042,49042.000000,49042.000000,49042.000000,49042.000000,49042.000000,49042.000000,49042.000000,4.904200e+04,49042.000000,49042.000000,49042.000000
mean,0 days 01:20:43.904131193,329.913120,0 days 00:47:10.453131193,9775.232760,195.439195,5.228722,60.969557,19.155459,0.263754,145080.017306,4.714717e-01,-7698.048346,-4496.700420,221.474165
std,0 days 00:27:13.550241102,302.617502,0 days 00:27:13.550241102,1747.639062,69.518368,1.720086,42.009235,38.492949,0.956928,91890.045384,2.986183e-01,5916.476267,2969.622559,4.588456
min,0 days 00:33:33.451000,0.000000,0 days 00:00:00,3766.000000,0.000000,1.000000,0.000000,0.000000,0.000000,-0.043213,-1.404323e-07,-16713.000000,-10797.000000,211.000000
25%,0 days 00:57:09.466250,3.187898,0 days 00:23:36.015250,8344.000000,135.000000,4.000000,8.000000,0.000000,0.000000,62808.668592,2.041116e-01,-13225.000000,-6399.000000,218.000000
50%,0 days 01:20:42.820000,360.861181,0 days 00:47:09.369000,10461.000000,190.000000,5.000000,83.000000,0.000000,0.000000,142519.969390,4.631522e-01,-8365.500000,-4308.000000,221.000000
75%,0 days 01:44:16.456000,608.043194,0 days 01:10:43.005000,11211.000000,257.000000,7.000000,100.000000,0.000000,0.000000,225336.217660,7.322831e-01,-1673.000000,-2365.000000,225.000000
max,0 days 02:07:56.725000,1028.321944,0 days 01:34:23.274000,12422.000000,342.000000,8.000000,100.000000,100.000000,14.000000,307708.879533,9.999725e-01,1652.000000,1053.000000,234.000000

#### c) Driver's telemetries from a specific lap

To catch the fastest lap :

In [18]:
fastest_driver = laps_driver.pick_fastest()

In [19]:
lap_number = 18
specific_lap_driver = laps_driver.iloc[lap_number]

In [20]:
telemetrie_spfc_lap = specific_lap_driver.get_telemetry()

In [21]:
telemetrie_spfc_lap.head()

,Date,SessionTime,DriverAhead,DistanceToDriverAhead,Time,RPM,Speed,nGear,Throttle,Brake,DRS,Source,Distance,RelativeDistance,Status,X,Y,Z
2,2020-09-27 11:49:51.946,0 days 01:09:51.892000,,41.465556,0 days 00:00:00,11575,184,4,100,0,0,interpolation,0.549173,0.000094,OnTrack,1227,-493,227
3,2020-09-27 11:49:51.959,0 days 01:09:51.905000,,41.465556,0 days 00:00:00.013000,11694,187,4,100,0,0,car,1.242778,0.000214,OnTrack,1224,-499,228
4,2020-09-27 11:49:52.069,0 days 01:09:52.015000,,41.465556,0 days 00:00:00.123000,11391,192,4,100,0,0,pos,7.193342,0.001237,OnTrack,1191,-547,228
5,2020-09-27 11:49:52.199,0 days 01:09:52.145000,5,41.465556,0 days 00:00:00.253000,11089,197,4,100,0,0,car,14.376111,0.002472,OnTrack,1151,-604,227
6,2020-09-27 11:49:52.289,0 days 01:09:52.235000,5,41.932222,0 days 00:00:00.343000,11132,200,4,100,0,0,pos,19.413597,0.003339,OnTrack,1124,-646,228

In [22]:
telemetrie_spfc_lap.shape

(870, 18)

In [23]:
laps_driver.get_pos_data()

,Date,Status,X,Y,Z,Source,Time,SessionTime
0,2020-09-27 11:13:33.573,OnTrack,256,-2013,227,pos,0 days 00:00:00.068000,0 days 00:33:33.519000
1,2020-09-27 11:13:33.793,OnTrack,256,-2013,227,pos,0 days 00:00:00.288000,0 days 00:33:33.739000
2,2020-09-27 11:13:34.013,OnTrack,250,-2014,227,pos,0 days 00:00:00.508000,0 days 00:33:33.959000
3,2020-09-27 11:13:34.233,OnTrack,240,-2015,227,pos,0 days 00:00:00.728000,0 days 00:33:34.179000
4,2020-09-27 11:13:34.453,OnTrack,227,-2016,226,pos,0 days 00:00:00.948000,0 days 00:33:34.399000
...,...,...,...,...,...,...,...,...
25815,2020-09-27 12:47:55.883,OnTrack,1458,-171,229,pos,0 days 01:34:22.378000,0 days 02:07:55.829000
25816,2020-09-27 12:47:56.103,OnTrack,1406,-247,229,pos,0 days 01:34:22.598000,0 days 02:07:56.049000
25817,2020-09-27 12:47:56.323,OnTrack,1350,-323,229,pos,0 days 01:34:22.818000,0 days 02:07:56.269000
25818,2020-09-27 12:47:56.543,OnTrack,1293,-401,228,pos,0 days 01:34:23.038000,0 days 02:07:56.489000
25819,2020-09-27 12:47:56.763,OnTrack,1236,-481,228,pos,0 days 01:34:23.258000,0 days 02:07:56.709000

### 3/ Weather data

In [24]:
weather = laps.get_weather_data()

In [25]:
weather

,Time,AirTemp,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed
33,0 days 00:33:41.120000,30.4,46,1012.5,True,41.1,34,0.5
35,0 days 00:35:41.130000,30.3,46.2,1012.6,True,40.7,320,0.7
39,0 days 00:39:41.173000,30.5,45,1012.7,True,40.5,11,0.7
41,0 days 00:41:41.174000,30.4,45.9,1012.8,True,40.3,56,0.5
44,0 days 00:44:41.176000,30.5,45.6,1012.7,True,40.4,0,0.4
...,...,...,...,...,...,...,...,...
120,0 days 02:00:41.447000,28.3,53.9,1013.2,True,39.1,285,1.5
121,0 days 02:01:41.445000,28,54.8,1013.1,True,38.6,258,1.5
123,0 days 02:03:41.448000,27.8,56,1013.1,True,38.6,254,1.2
125,0 days 02:05:41.450000,28.1,54.9,1013.1,True,38.7,218,1.6
127,0 days 02:07:41.451000,28,55.8,1013.1,True,38.7,243,1.7

In [26]:
weather.describe()

                            Time
count                        948
mean   0 days 01:23:01.965592827
std    0 days 00:26:25.172061947
min       0 days 00:33:41.120000
25%       0 days 01:01:41.276000
50%       0 days 01:23:41.332000
75%       0 days 01:45:41.420000
max       0 days 02:07:41.451000

### 4/ driver data

In [27]:
driver_data = session.get_driver('VER')

In [33]:
driver_data.info

{'number': '33',
 'position': '2',
 'positionText': '2',
 'points': '18',
 'Driver': {'driverId': 'max_verstappen',
  'permanentNumber': '33',
  'code': 'VER',
  'url': 'http://en.wikipedia.org/wiki/Max_Verstappen',
  'givenName': 'Max',
  'familyName': 'Verstappen',
  'dateOfBirth': '1997-09-30',
  'nationality': 'Dutch'},
 'Constructor': {'constructorId': 'red_bull',
  'url': 'http://en.wikipedia.org/wiki/Red_Bull_Racing',
  'name': 'Red Bull',
  'nationality': 'Austrian'},
 'grid': '2',
 'laps': '53',
 'status': 'Finished',
 'Time': {'millis': '5648093', 'time': '+7.729'},
 'FastestLap': {'rank': '3',
  'lap': '53',
  'Time': {'time': '1:37.332'},
  'AverageSpeed': {'units': 'kph', 'speed': '216.298'}}}

In [35]:
int(driver_data.info['position'])

2

In [36]:
int(driver_data.info['grid'])

2

In [37]:
str(driver_data.info['status'])

'Finished'

In [29]:
[FP1.pos,FP1.temps,FP2.pos,FP2.temps,FP3,C,GP,Id : driver, week_end_number]

SyntaxError: invalid syntax (<ipython-input-29-2355831836ad>, line 1)

In [ ]:
clustering non supervisé : sur le type du circuit ( meilleur tour de Quali)

In [ ]:
pit stop strategie : prediction defaillance du pneu

In [ ]:
[Quan,